In [1]:
import pandas as pd
import numpy as np

In [3]:
reviews_df = pd.read_csv("reviews_sample.csv")
reviews_df.head()

,review_id,product_name,reviewer_name,rating,title,review_body,date,verified_purchase,helpful_votes,location,platform
0,FK23756669,boAt Rockerz 255 Pro Bluetooth Earphones,Divya_I95,3,Decent,Mixed feelings. bass is good but microphone is...,22 May 2024,Yes,0,Lucknow,Flipkart
1,FK90801586,boAt Rockerz 255 Pro Bluetooth Earphones,Rahul_M72,4,Worth buying,Good product overall. sound quality is solid. ...,01 Jun 2025,No,0,Surat,Flipkart
2,FK31429110,boAt Rockerz 255 Pro Bluetooth Earphones,Nikhil_O55,2,Poor quality,Waste of money. fit & comfort doesn't work as ...,07 Jan 2024,Yes,1,Bangalore,Flipkart
3,FK56164955,boAt Rockerz 255 Pro Bluetooth Earphones,Lakshmi_E34,5,Amazing product!,Absolutely love this product! noise cancellati...,02 Jan 2025,No,0,Ahmedabad,Flipkart
4,FK87490893,boAt Rockerz 255 Pro Bluetooth Earphones,Suresh_V91,3,Average,Average product. bass is okay but durability i...,05 Jan 2025,Yes,1,Surat,Flipkart

In [4]:
import re

STOPWORDS = {"and", "a", "the"}


def preprocess_text(text, remove_stopwords=True):
    """Lowercase, remove punctuation, tokenize, and optionally remove stopwords."""
    text = "" if pd.isna(text) else str(text)
    text = text.lower()
    text = re.sub(r"[^\w\s]", " ", text)
    tokens = text.split()

    if remove_stopwords:
        tokens = [token for token in tokens if token not in STOPWORDS]

    return tokens


reviews_df["text"] = reviews_df["review_body"].fillna(reviews_df["title"])
reviews_df["tokens"] = reviews_df["text"].apply(preprocess_text)
reviews_df["processed_text"] = reviews_df["tokens"].str.join(" ")

reviews_df[["text", "tokens", "processed_text"]].head()

,text,tokens,processed_text
0,Mixed feelings. bass is good but microphone is...,"[mixed, feelings, bass, is, good, but, microph...",mixed feelings bass is good but microphone is ...
1,Good product overall. sound quality is solid. ...,"[good, product, overall, sound, quality, is, s...",good product overall sound quality is solid mi...
2,Waste of money. fit & comfort doesn't work as ...,"[waste, of, money, fit, comfort, doesn, t, wor...",waste of money fit comfort doesn t work as sho...
3,Absolutely love this product! noise cancellati...,"[absolutely, love, this, product, noise, cance...",absolutely love this product noise cancellatio...
4,Average product. bass is okay but durability i...,"[average, product, bass, is, okay, but, durabi...",average product bass is okay but durability is...

In [5]:
reviews_df

,review_id,product_name,reviewer_name,rating,title,review_body,date,verified_purchase,helpful_votes,location,platform,text,tokens,processed_text
0,FK23756669,boAt Rockerz 255 Pro Bluetooth Earphones,Divya_I95,3,Decent,Mixed feelings. bass is good but microphone is...,22 May 2024,Yes,0,Lucknow,Flipkart,Mixed feelings. bass is good but microphone is...,"[mixed, feelings, bass, is, good, but, microph...",mixed feelings bass is good but microphone is ...
1,FK90801586,boAt Rockerz 255 Pro Bluetooth Earphones,Rahul_M72,4,Worth buying,Good product overall. sound quality is solid. ...,01 Jun 2025,No,0,Surat,Flipkart,Good product overall. sound quality is solid. ...,"[good, product, overall, sound, quality, is, s...",good product overall sound quality is solid mi...
2,FK31429110,boAt Rockerz 255 Pro Bluetooth Earphones,Nikhil_O55,2,Poor quality,Waste of money. fit & comfort doesn't work as ...,07 Jan 2024,Yes,1,Bangalore,Flipkart,Waste of money. fit & comfort doesn't work as ...,"[waste, of, money, fit, comfort, doesn, t, wor...",waste of money fit comfort doesn t work as sho...
3,FK56164955,boAt Rockerz 255 Pro Bluetooth Earphones,Lakshmi_E34,5,Amazing product!,Absolutely love this product! noise cancellati...,02 Jan 2025,No,0,Ahmedabad,Flipkart,Absolutely love this product! noise cancellati...,"[absolutely, love, this, product, noise, cance...",absolutely love this product noise cancellatio...
4,FK87490893,boAt Rockerz 255 Pro Bluetooth Earphones,Suresh_V91,3,Average,Average product. bass is okay but durability i...,05 Jan 2025,Yes,1,Surat,Flipkart,Average product. bass is okay but durability i...,"[average, product, bass, is, okay, but, durabi...",average product bass is okay but durability is...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,FK30486849,boAt Rockerz 255 Pro Bluetooth Earphones,Divya_I61,5,Love it!,Fantastic! noise cancellation exceeded my expe...,18 Jan 2025,Yes,2,Bhopal,Flipkart,Fantastic! noise cancellation exceeded my expe...,"[fantastic, noise, cancellation, exceeded, my,...",fantastic noise cancellation exceeded my expec...
116,FK27463800,boAt Rockerz 255 Pro Bluetooth Earphones,Rekha_F8,5,Outstanding!,Absolutely love this product! bass is outstand...,16 Jan 2025,No,2,Delhi,Flipkart,Absolutely love this product! bass is outstand...,"[absolutely, love, this, product, bass, is, ou...",absolutely love this product bass is outstandi...
117,FK57197152,boAt Rockerz 255 Pro Bluetooth Earphones,Sneha_P74,4,Pretty good,Good product overall. noise cancellation is so...,15 Nov 2024,Yes,12,Bangalore,Flipkart,Good product overall. noise cancellation is so...,"[good, product, overall, noise, cancellation, ...",good product overall noise cancellation is sol...
118,FK25419645,boAt Rockerz 255 Pro Bluetooth Earphones,Prasad_Z36,2,Bad experience,Disappointed with build quality. earphone grip...,11 Jan 2025,Yes,0,Indore,Flipkart,Disappointed with build quality. earphone grip...,"[disappointed, with, build, quality, earphone,...",disappointed with build quality earphone grip ...
119,FK55610493,boAt Rockerz 255 Pro Bluetooth Earphones,Pooja_A1,4,Worth buying,Good product overall. sound quality is solid. ...,12 Nov 2024,Yes,0,Lucknow,Flipkart,Good product overall. sound quality is solid. ...,"[good, product, overall, sound, quality, is, s...",good product overall sound quality is solid so...